
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedCsharpSDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    
    public class TicketingNote
    {

        [JsonProperty("agent_id")]
        public string? AgentId { get; set; }

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        [JsonProperty("customer_id")]
        public string? CustomerId { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("id")]
        public string? Id { get; set; }

        [JsonProperty("raw")]
        public PropertyTicketingNoteRaw? Raw { get; set; }

        [JsonProperty("ticket_id")]
        public string? TicketId { get; set; }

        [JsonProperty("updated_at")]
        public string? UpdatedAt { get; set; }
    }
}