//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class AccountingInvoiceType : IEquatable<AccountingInvoiceType>
    {
        public static readonly AccountingInvoiceType Bill = new AccountingInvoiceType("BILL");
        public static readonly AccountingInvoiceType Invoice = new AccountingInvoiceType("INVOICE");
        public static readonly AccountingInvoiceType Creditmemo = new AccountingInvoiceType("CREDITMEMO");

        private static readonly Dictionary <string, AccountingInvoiceType> _knownValues =
            new Dictionary <string, AccountingInvoiceType> ()
            {
                ["BILL"] = Bill,
                ["INVOICE"] = Invoice,
                ["CREDITMEMO"] = Creditmemo
            };

        private static readonly ConcurrentDictionary<string, AccountingInvoiceType> _values =
            new ConcurrentDictionary<string, AccountingInvoiceType>(_knownValues);

        private AccountingInvoiceType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static AccountingInvoiceType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new AccountingInvoiceType(value));
        }

        public static implicit operator AccountingInvoiceType(string value) => Of(value);
        public static implicit operator string(AccountingInvoiceType accountinginvoicetype) => accountinginvoicetype.Value;

        public static AccountingInvoiceType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as AccountingInvoiceType);

        public bool Equals(AccountingInvoiceType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}