//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using UnifiedTo.Models.Components;
    using UnifiedTo.Utils;
    

    public class CrmMetadata2Type
    {
        private CrmMetadata2Type(string value) { Value = value; }

        public string Value { get; private set; }
        public static CrmMetadata2Type Str { get { return new CrmMetadata2Type("str"); } }
        
        public static CrmMetadata2Type CrmMetadataSchemasExtraData22 { get { return new CrmMetadata2Type("CrmMetadata_Schemas_extra_data_2_2"); } }
        
        public static CrmMetadata2Type Null { get { return new CrmMetadata2Type("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CrmMetadata2Type v) { return v.Value; }
        public static CrmMetadata2Type FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "CrmMetadata_Schemas_extra_data_2_2": return CrmMetadataSchemasExtraData22;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for CrmMetadata2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CrmMetadata2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(CrmMetadata2.CrmMetadata2Converter))]
    public class CrmMetadata2 {
        public CrmMetadata2(CrmMetadata2Type type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public CrmMetadataSchemasExtraData22? CrmMetadataSchemasExtraData22 { get; set; }

        public CrmMetadata2Type Type { get; set; }


        public static CrmMetadata2 CreateStr(string str) {
            CrmMetadata2Type typ = CrmMetadata2Type.Str;

            CrmMetadata2 res = new CrmMetadata2(typ);
            res.Str = str;
            return res;
        }

        public static CrmMetadata2 CreateCrmMetadataSchemasExtraData22(CrmMetadataSchemasExtraData22 crmMetadataSchemasExtraData22) {
            CrmMetadata2Type typ = CrmMetadata2Type.CrmMetadataSchemasExtraData22;

            CrmMetadata2 res = new CrmMetadata2(typ);
            res.CrmMetadataSchemasExtraData22 = crmMetadataSchemasExtraData22;
            return res;
        }

        public static CrmMetadata2 CreateNull() {
            CrmMetadata2Type typ = CrmMetadata2Type.Null;
            return new CrmMetadata2(typ);
        }

        public class CrmMetadata2Converter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(CrmMetadata2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CrmMetadata2(CrmMetadata2Type.CrmMetadataSchemasExtraData22)
                    {
                        CrmMetadataSchemasExtraData22 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CrmMetadataSchemasExtraData22>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CrmMetadataSchemasExtraData22), new CrmMetadata2(CrmMetadata2Type.CrmMetadataSchemasExtraData22), "CrmMetadataSchemasExtraData22"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new CrmMetadata2(CrmMetadata2Type.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                CrmMetadata2 res = (CrmMetadata2)value;
                if (CrmMetadata2Type.FromString(res.Type).Equals(CrmMetadata2Type.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.CrmMetadataSchemasExtraData22 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CrmMetadataSchemasExtraData22));
                    return;
                }

            }

        }

    }
}