//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using UnifiedTo.Models.Components;
    using UnifiedTo.Utils;

    public class CrmMetadataSchemas5Type
    {
        private CrmMetadataSchemas5Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static CrmMetadataSchemas5Type CrmMetadataSchemas1 { get { return new CrmMetadataSchemas5Type("CrmMetadata_Schemas_1"); } }

        public static CrmMetadataSchemas5Type Str { get { return new CrmMetadataSchemas5Type("str"); } }

        public static CrmMetadataSchemas5Type Number { get { return new CrmMetadataSchemas5Type("number"); } }

        public static CrmMetadataSchemas5Type Boolean { get { return new CrmMetadataSchemas5Type("boolean"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CrmMetadataSchemas5Type v) { return v.Value; }
        public static CrmMetadataSchemas5Type FromString(string v) {
            switch(v) {
                case "CrmMetadata_Schemas_1": return CrmMetadataSchemas1;
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                default: throw new ArgumentException("Invalid value for CrmMetadataSchemas5Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CrmMetadataSchemas5Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(CrmMetadataSchemas5.CrmMetadataSchemas5Converter))]
    public class CrmMetadataSchemas5
    {
        public CrmMetadataSchemas5(CrmMetadataSchemas5Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public CrmMetadataSchemas1? CrmMetadataSchemas1 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        public CrmMetadataSchemas5Type Type { get; set; }
        public static CrmMetadataSchemas5 CreateCrmMetadataSchemas1(CrmMetadataSchemas1 crmMetadataSchemas1)
        {
            CrmMetadataSchemas5Type typ = CrmMetadataSchemas5Type.CrmMetadataSchemas1;

            CrmMetadataSchemas5 res = new CrmMetadataSchemas5(typ);
            res.CrmMetadataSchemas1 = crmMetadataSchemas1;
            return res;
        }
        public static CrmMetadataSchemas5 CreateStr(string str)
        {
            CrmMetadataSchemas5Type typ = CrmMetadataSchemas5Type.Str;

            CrmMetadataSchemas5 res = new CrmMetadataSchemas5(typ);
            res.Str = str;
            return res;
        }
        public static CrmMetadataSchemas5 CreateNumber(double number)
        {
            CrmMetadataSchemas5Type typ = CrmMetadataSchemas5Type.Number;

            CrmMetadataSchemas5 res = new CrmMetadataSchemas5(typ);
            res.Number = number;
            return res;
        }
        public static CrmMetadataSchemas5 CreateBoolean(bool boolean)
        {
            CrmMetadataSchemas5Type typ = CrmMetadataSchemas5Type.Boolean;

            CrmMetadataSchemas5 res = new CrmMetadataSchemas5(typ);
            res.Boolean = boolean;
            return res;
        }

        public class CrmMetadataSchemas5Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CrmMetadataSchemas5);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CrmMetadataSchemas5(CrmMetadataSchemas5Type.CrmMetadataSchemas1)
                    {
                        CrmMetadataSchemas1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CrmMetadataSchemas1>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CrmMetadataSchemas1), new CrmMetadataSchemas5(CrmMetadataSchemas5Type.CrmMetadataSchemas1), "CrmMetadataSchemas1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new CrmMetadataSchemas5(CrmMetadataSchemas5Type.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new CrmMetadataSchemas5(CrmMetadataSchemas5Type.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new CrmMetadataSchemas5(CrmMetadataSchemas5Type.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CrmMetadataSchemas5 res = (CrmMetadataSchemas5)value;

                if (res.CrmMetadataSchemas1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CrmMetadataSchemas1));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}