//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class HrisTimeoffType : IEquatable<HrisTimeoffType>
    {
        public static readonly HrisTimeoffType Vacation = new HrisTimeoffType("VACATION");
        public static readonly HrisTimeoffType Sick = new HrisTimeoffType("SICK");
        public static readonly HrisTimeoffType Holiday = new HrisTimeoffType("HOLIDAY");
        public static readonly HrisTimeoffType Bereavement = new HrisTimeoffType("BEREAVEMENT");
        public static readonly HrisTimeoffType Parental = new HrisTimeoffType("PARENTAL");
        public static readonly HrisTimeoffType Unpaid = new HrisTimeoffType("UNPAID");
        public static readonly HrisTimeoffType InLieu = new HrisTimeoffType("IN_LIEU");
        public static readonly HrisTimeoffType Other = new HrisTimeoffType("OTHER");

        private static readonly Dictionary <string, HrisTimeoffType> _knownValues =
            new Dictionary <string, HrisTimeoffType> ()
            {
                ["VACATION"] = Vacation,
                ["SICK"] = Sick,
                ["HOLIDAY"] = Holiday,
                ["BEREAVEMENT"] = Bereavement,
                ["PARENTAL"] = Parental,
                ["UNPAID"] = Unpaid,
                ["IN_LIEU"] = InLieu,
                ["OTHER"] = Other
            };

        private static readonly ConcurrentDictionary<string, HrisTimeoffType> _values =
            new ConcurrentDictionary<string, HrisTimeoffType>(_knownValues);

        private HrisTimeoffType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static HrisTimeoffType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new HrisTimeoffType(value));
        }

        public static implicit operator HrisTimeoffType(string value) => Of(value);
        public static implicit operator string(HrisTimeoffType hristimeofftype) => hristimeofftype.Value;

        public static HrisTimeoffType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as HrisTimeoffType);

        public bool Equals(HrisTimeoffType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}