//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ListUserId : IEquatable<ListUserId>
    {
        public static readonly ListUserId SupportedRequired = new ListUserId("supported-required");
        public static readonly ListUserId Supported = new ListUserId("supported");
        public static readonly ListUserId NotSupported = new ListUserId("not-supported");

        private static readonly Dictionary <string, ListUserId> _knownValues =
            new Dictionary <string, ListUserId> ()
            {
                ["supported-required"] = SupportedRequired,
                ["supported"] = Supported,
                ["not-supported"] = NotSupported
            };

        private static readonly ConcurrentDictionary<string, ListUserId> _values =
            new ConcurrentDictionary<string, ListUserId>(_knownValues);

        private ListUserId(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ListUserId Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ListUserId(value));
        }

        public static implicit operator ListUserId(string value) => Of(value);
        public static implicit operator string(ListUserId listuserid) => listuserid.Value;

        public static ListUserId[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ListUserId);

        public bool Equals(ListUserId? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}