//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class PropertyAdsReportMetricsInsertionorderPacingPeriod : IEquatable<PropertyAdsReportMetricsInsertionorderPacingPeriod>
    {
        public static readonly PropertyAdsReportMetricsInsertionorderPacingPeriod Unspecified = new PropertyAdsReportMetricsInsertionorderPacingPeriod("UNSPECIFIED");
        public static readonly PropertyAdsReportMetricsInsertionorderPacingPeriod Daily = new PropertyAdsReportMetricsInsertionorderPacingPeriod("DAILY");
        public static readonly PropertyAdsReportMetricsInsertionorderPacingPeriod Flight = new PropertyAdsReportMetricsInsertionorderPacingPeriod("FLIGHT");

        private static readonly Dictionary <string, PropertyAdsReportMetricsInsertionorderPacingPeriod> _knownValues =
            new Dictionary <string, PropertyAdsReportMetricsInsertionorderPacingPeriod> ()
            {
                ["UNSPECIFIED"] = Unspecified,
                ["DAILY"] = Daily,
                ["FLIGHT"] = Flight
            };

        private static readonly ConcurrentDictionary<string, PropertyAdsReportMetricsInsertionorderPacingPeriod> _values =
            new ConcurrentDictionary<string, PropertyAdsReportMetricsInsertionorderPacingPeriod>(_knownValues);

        private PropertyAdsReportMetricsInsertionorderPacingPeriod(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static PropertyAdsReportMetricsInsertionorderPacingPeriod Of(string value)
        {
            return _values.GetOrAdd(value, _ => new PropertyAdsReportMetricsInsertionorderPacingPeriod(value));
        }

        public static implicit operator PropertyAdsReportMetricsInsertionorderPacingPeriod(string value) => Of(value);
        public static implicit operator string(PropertyAdsReportMetricsInsertionorderPacingPeriod propertyadsreportmetricsinsertionorderpacingperiod) => propertyadsreportmetricsinsertionorderpacingperiod.Value;

        public static PropertyAdsReportMetricsInsertionorderPacingPeriod[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as PropertyAdsReportMetricsInsertionorderPacingPeriod);

        public bool Equals(PropertyAdsReportMetricsInsertionorderPacingPeriod? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}