//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class SigningSignatoryRole : IEquatable<SigningSignatoryRole>
    {
        public static readonly SigningSignatoryRole Signer = new SigningSignatoryRole("SIGNER");
        public static readonly SigningSignatoryRole Cc = new SigningSignatoryRole("CC");
        public static readonly SigningSignatoryRole Approver = new SigningSignatoryRole("APPROVER");
        public static readonly SigningSignatoryRole InPersonSigner = new SigningSignatoryRole("IN_PERSON_SIGNER");
        public static readonly SigningSignatoryRole Viewer = new SigningSignatoryRole("VIEWER");

        private static readonly Dictionary <string, SigningSignatoryRole> _knownValues =
            new Dictionary <string, SigningSignatoryRole> ()
            {
                ["SIGNER"] = Signer,
                ["CC"] = Cc,
                ["APPROVER"] = Approver,
                ["IN_PERSON_SIGNER"] = InPersonSigner,
                ["VIEWER"] = Viewer
            };

        private static readonly ConcurrentDictionary<string, SigningSignatoryRole> _values =
            new ConcurrentDictionary<string, SigningSignatoryRole>(_knownValues);

        private SigningSignatoryRole(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static SigningSignatoryRole Of(string value)
        {
            return _values.GetOrAdd(value, _ => new SigningSignatoryRole(value));
        }

        public static implicit operator SigningSignatoryRole(string value) => Of(value);
        public static implicit operator string(SigningSignatoryRole signingsignatoryrole) => signingsignatoryrole.Value;

        public static SigningSignatoryRole[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as SigningSignatoryRole);

        public bool Equals(SigningSignatoryRole? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}