//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class VirtualWebhookSpaceId : IEquatable<VirtualWebhookSpaceId>
    {
        public static readonly VirtualWebhookSpaceId SupportedRequired = new VirtualWebhookSpaceId("supported-required");
        public static readonly VirtualWebhookSpaceId Supported = new VirtualWebhookSpaceId("supported");
        public static readonly VirtualWebhookSpaceId NotSupported = new VirtualWebhookSpaceId("not-supported");

        private static readonly Dictionary <string, VirtualWebhookSpaceId> _knownValues =
            new Dictionary <string, VirtualWebhookSpaceId> ()
            {
                ["supported-required"] = SupportedRequired,
                ["supported"] = Supported,
                ["not-supported"] = NotSupported
            };

        private static readonly ConcurrentDictionary<string, VirtualWebhookSpaceId> _values =
            new ConcurrentDictionary<string, VirtualWebhookSpaceId>(_knownValues);

        private VirtualWebhookSpaceId(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static VirtualWebhookSpaceId Of(string value)
        {
            return _values.GetOrAdd(value, _ => new VirtualWebhookSpaceId(value));
        }

        public static implicit operator VirtualWebhookSpaceId(string value) => Of(value);
        public static implicit operator string(VirtualWebhookSpaceId virtualwebhookspaceid) => virtualwebhookspaceid.Value;

        public static VirtualWebhookSpaceId[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as VirtualWebhookSpaceId);

        public bool Equals(VirtualWebhookSpaceId? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}