//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class VirtualWebhookCustomerId : IEquatable<VirtualWebhookCustomerId>
    {
        public static readonly VirtualWebhookCustomerId SupportedRequired = new VirtualWebhookCustomerId("supported-required");
        public static readonly VirtualWebhookCustomerId Supported = new VirtualWebhookCustomerId("supported");
        public static readonly VirtualWebhookCustomerId NotSupported = new VirtualWebhookCustomerId("not-supported");

        private static readonly Dictionary <string, VirtualWebhookCustomerId> _knownValues =
            new Dictionary <string, VirtualWebhookCustomerId> ()
            {
                ["supported-required"] = SupportedRequired,
                ["supported"] = Supported,
                ["not-supported"] = NotSupported
            };

        private static readonly ConcurrentDictionary<string, VirtualWebhookCustomerId> _values =
            new ConcurrentDictionary<string, VirtualWebhookCustomerId>(_knownValues);

        private VirtualWebhookCustomerId(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static VirtualWebhookCustomerId Of(string value)
        {
            return _values.GetOrAdd(value, _ => new VirtualWebhookCustomerId(value));
        }

        public static implicit operator VirtualWebhookCustomerId(string value) => Of(value);
        public static implicit operator string(VirtualWebhookCustomerId virtualwebhookcustomerid) => virtualwebhookcustomerid.Value;

        public static VirtualWebhookCustomerId[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as VirtualWebhookCustomerId);

        public bool Equals(VirtualWebhookCustomerId? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}