//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using UnifiedTo.Utils;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class VirtualWebhookLabelId : IEquatable<VirtualWebhookLabelId>
    {
        public static readonly VirtualWebhookLabelId SupportedRequired = new VirtualWebhookLabelId("supported-required");
        public static readonly VirtualWebhookLabelId Supported = new VirtualWebhookLabelId("supported");
        public static readonly VirtualWebhookLabelId NotSupported = new VirtualWebhookLabelId("not-supported");

        private static readonly Dictionary <string, VirtualWebhookLabelId> _knownValues =
            new Dictionary <string, VirtualWebhookLabelId> ()
            {
                ["supported-required"] = SupportedRequired,
                ["supported"] = Supported,
                ["not-supported"] = NotSupported
            };

        private static readonly ConcurrentDictionary<string, VirtualWebhookLabelId> _values =
            new ConcurrentDictionary<string, VirtualWebhookLabelId>(_knownValues);

        private VirtualWebhookLabelId(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static VirtualWebhookLabelId Of(string value)
        {
            return _values.GetOrAdd(value, _ => new VirtualWebhookLabelId(value));
        }

        public static implicit operator VirtualWebhookLabelId(string value) => Of(value);
        public static implicit operator string(VirtualWebhookLabelId virtualwebhooklabelid) => virtualwebhooklabelid.Value;

        public static VirtualWebhookLabelId[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as VirtualWebhookLabelId);

        public bool Equals(VirtualWebhookLabelId? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}