//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnifiedTo.Utils;
    
    public enum CreateCalendarCalendarQueryParamFields
    {
        [JsonProperty("id")]
        Id,
        [JsonProperty("created_at")]
        CreatedAt,
        [JsonProperty("updated_at")]
        UpdatedAt,
        [JsonProperty("name")]
        Name,
        [JsonProperty("description")]
        Description,
        [JsonProperty("timezone")]
        Timezone,
        [JsonProperty("primary")]
        Primary,
        [JsonProperty("is_primary")]
        IsPrimary,
        [JsonProperty("raw")]
        Raw,
    }

    public static class CreateCalendarCalendarQueryParamFieldsExtension
    {
        public static string Value(this CreateCalendarCalendarQueryParamFields value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreateCalendarCalendarQueryParamFields ToEnum(this string value)
        {
            foreach(var field in typeof(CreateCalendarCalendarQueryParamFields).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreateCalendarCalendarQueryParamFields)
                    {
                        return (CreateCalendarCalendarQueryParamFields)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreateCalendarCalendarQueryParamFields");
        }
    }

}