//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnifiedTo.Utils;
    
    public enum CreateCrmCompany2QueryParamFields
    {
        [JsonProperty("id")]
        Id,
        [JsonProperty("created_at")]
        CreatedAt,
        [JsonProperty("updated_at")]
        UpdatedAt,
        [JsonProperty("name")]
        Name,
        [JsonProperty("deal_ids")]
        DealIds,
        [JsonProperty("contact_ids")]
        ContactIds,
        [JsonProperty("emails")]
        Emails,
        [JsonProperty("telephones")]
        Telephones,
        [JsonProperty("websites")]
        Websites,
        [JsonProperty("address")]
        Address,
        [JsonProperty("is_active")]
        IsActive,
        [JsonProperty("tags")]
        Tags,
        [JsonProperty("description")]
        Description,
        [JsonProperty("industry")]
        Industry,
        [JsonProperty("link_urls")]
        LinkUrls,
        [JsonProperty("employees")]
        Employees,
        [JsonProperty("timezone")]
        Timezone,
        [JsonProperty("user_id")]
        UserId,
        [JsonProperty("metadata")]
        Metadata,
        [JsonProperty("domains")]
        Domains,
        [JsonProperty("raw")]
        Raw,
    }

    public static class CreateCrmCompany2QueryParamFieldsExtension
    {
        public static string Value(this CreateCrmCompany2QueryParamFields value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreateCrmCompany2QueryParamFields ToEnum(this string value)
        {
            foreach(var field in typeof(CreateCrmCompany2QueryParamFields).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreateCrmCompany2QueryParamFields)
                    {
                        return (CreateCrmCompany2QueryParamFields)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreateCrmCompany2QueryParamFields");
        }
    }

}