//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace UnifiedTo.Models.Requests
{
    using Newtonsoft.Json;
    using System;
    using UnifiedTo.Utils;

    public enum GetCdpSegmentQueryParamFields
    {
        [JsonProperty("id")]
        Id,
        [JsonProperty("created_at")]
        CreatedAt,
        [JsonProperty("updated_at")]
        UpdatedAt,
        [JsonProperty("name")]
        Name,
        [JsonProperty("slug")]
        Slug,
        [JsonProperty("description")]
        Description,
        [JsonProperty("definition")]
        Definition,
        [JsonProperty("type")]
        Type,
        [JsonProperty("compute_mode")]
        ComputeMode,
        [JsonProperty("size")]
        Size,
        [JsonProperty("is_active")]
        IsActive,
        [JsonProperty("source_id")]
        SourceId,
        [JsonProperty("raw")]
        Raw,
    }

    public static class GetCdpSegmentQueryParamFieldsExtension
    {
        public static string Value(this GetCdpSegmentQueryParamFields value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetCdpSegmentQueryParamFields ToEnum(this string value)
        {
            foreach(var field in typeof(GetCdpSegmentQueryParamFields).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetCdpSegmentQueryParamFields)
                    {
                        return (GetCdpSegmentQueryParamFields)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetCdpSegmentQueryParamFields");
        }
    }
}