workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api.unified.to/openapi.json
        registry:
            location: registry.speakeasyapi.dev/unified/unified/my-source
targets:
    csharp-target:
        target: csharp
        source: my-source
        publish:
            nuget:
                apiKey: $NUGET_API_KEY
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/unified/unified/my-source-csharp-code-samples
            blocking: false
